In [1]:
import pandas as pd

# Carregar a base
# Reproduzir comportamento básico

%run 00_funcoes_compartilhadas.ipynb
%run 01_conexao_dados.ipynb

df_vendas = carregar_a_partir_de_arquivos_separados("Vendas")

df_vendas = padronizar_textos_tabela(df_vendas)

df_vendas = eliminar_linhas_colunas_em_branco(df_vendas)

In [10]:
salvar_base(df_vendas, "05.Base Vendas")

Base salva com sucesso em: C:\Users\Hashtag\Hashtag Treinamentos\InCompany\Data Analytics\00.08 Petros T3\Projeto\dados\bases_limpas\05.Base Vendas.csv

In [11]:
del df_vendas

In [2]:
df_vendas.head(5)

,SKU,Tamanho Pedido,Loja,Data da Venda,Código Cliente,Data da Entrega
0,hl0977,4,salvador,2017-06-14,262,2017-06-15
1,hl0977,1,fortaleza,2017-08-23,274,2017-08-25
2,hl0997,1,belo horizonte,2017-11-04,201,2017-11-08
3,hl0994,5,recife,2017-05-05,4,2017-05-06
4,hl0995,1,salvador,2017-05-06,408,2017-05-17

In [8]:
# Criar indicadores com Python
# Total faturado e marge de lucro

# Antes é necessário importar as informações da base de produtos. (realizar o que seria um PROCX do excel)
df_produtos_limpa = carregar_base("02.Base Produtos.csv", dir_destino)
df_vendas_completo = df_vendas.merge(df_produtos_limpa, on='SKU', how='left')

In [5]:
display(df_vendas_completo)

,SKU,Tamanho Pedido,Loja,Data da Venda,Código Cliente,Data da Entrega,Marca,Categoria,Preco Unitario,Custo Unitario,Nome Produto,cor
0,hl0977,4,salvador,2017-06-14,262,2017-06-15,samsung,celular,1100.0,600.0,galaxy j7 prime 32gb,dourado
1,hl0977,1,fortaleza,2017-08-23,274,2017-08-25,samsung,celular,1100.0,600.0,galaxy j7 prime 32gb,dourado
2,hl0997,1,belo horizonte,2017-11-04,201,2017-11-08,sony,video game,2400.0,1600.0,console playstation 4 slim 1tb,preto
3,hl0994,5,recife,2017-05-05,4,2017-05-06,acer,notebook,2500.0,1400.0,notebook aspire 5,prata
4,hl0995,1,salvador,2017-05-06,408,2017-05-17,apple,notebook,6800.0,4300.0,macbook air 13' i5 128gb,prata
...,...,...,...,...,...,...,...,...,...,...,...,...
66875,hl1038,5,guarulhos,2025-12-31,756,2025-12-31,jbl,Ã¡udio,650.0,380.0,caixa de som bluetooth flip 6,preto
66876,hl1044,4,nova iguaçu,2025-12-31,842,2025-12-31,lg,televisÃ£o,6800.0,4600.0,smart tv 55' oled evo c4,preto
66877,hl1032,2,goiânia,2025-12-31,785,2025-12-31,samsung,tablet,2700.0,1750.0,galaxy tab s9 fe 128gb,cinza
66878,hl1054,2,são paulo,2025-12-30,806,2025-12-30,dji,cÃ¢mera,7500.0,5200.0,drone mini 4 pro fly more combo,cinza
66879,hl1036,3,belo horizonte,2025-12-31,745,2025-12-31,samsung,smart watch,2100.0,1300.0,galaxy watch 7,grafite

In [9]:
# Calcular o faturamento por venda
df_vendas_completo['Faturamento'] = df_vendas_completo['Tamanho Pedido'] * df_vendas_completo['Preco Unitario']

In [ ]:
# Calcular lucro e margem lucro
# df_vendas_completo['Lucro'] = 

# df_vendas_completo['Margem Lucro (%)'] =

In [ ]:

# def classificar_margem(margem):
#     if margem < 0.20:
#         return "Crítico"
#     elif margem <= 0.30:
#         return "Atenção"
#     else:
#         return "Saudável"

In [ ]:
# Indicadores Básicos
# faturamento_total = 
# lucro_total = 
# margem_lucro =
# situacao_lucro = 

# quantidade_vendida = 
# quantidade_vendas = 

# ticket_medio = 

# Identificando o produto mais lucrativo (Preparação para análise futura)
# top_produto =

In [ ]:
# indicadores = pd.DataFrame({
#     "Indicador": ["Faturamento Total", "Lucro Total", "Margem Lucro", "Situação Lucro", "Quantidade Vendida", "Quantidade de Vendas", "Ticket Médio", "Top Produto"],
#     "Valor": [faturamento_total, lucro_total, margem_lucro, situacao_lucro, quantidade_vendida, quantidade_vendas, ticket_medio, top_produto],
#     })

In [ ]:
# salvar_base(indicadores, "Indicadores")